name: Deploy Nuxt Frontend

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd /root/omni-app
            git pull
            docker compose down
            docker compose up -d --build

      - name: Notify Telegram (Success)
        if: success()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="✅ Деплой *OMNI-APP (frontend)* завершён успешно на сервере.\n\nGitHub Actions: ${{ github.workflow }}\nCommit: ${{ github.sha }}" \
            -d parse_mode=Markdown

      - name: Notify Telegram (Failure)
        if: failure()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="❌ Ошибка при деплое *OMNI-APP (frontend)*!\n\nПроверь GitHub Actions: ${{ github.workflow }}" \
            -d parse_mode=Markdown
